#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\App;
use App\Services\HttpService;
use App\Services\CommandLineService;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->safeLoad();

$httpClient = new HttpService;
$commandLine = new CommandLineService();
$app = new App($httpClient, $commandLine);

$app->run();
